name: Update Weather Data
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:  


jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Fetch weather data
        run: |
          curl "https://api.open-meteo.com/v1/forecast?latitude=44.6464&longitude=-63.5729&hourly=temperature_2m,weather_code&timezone=auto" > data/weather-data.json
        
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add weather-data.json
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update weather data [skip ci]"
          git push
          